Repository ladybug-tools/honeybee-schema, pull requests merged in 2020-04, with the labels that each got.

#59 feat(honeybee_schema): Detailed equivalents for abridged schemas.
  honeybee_schema/energy/construction.py
  honeybee_schema/energy/constructionset.py
  honeybee_schema/energy/load.py
  honeybee_schema/energy/programtype.py
  honeybee_schema/energy/schedule.py
Labels: enhancement

#62 feat(docs): Improving descriptions of ModelEnergyProerties
  honeybee_schema/energy/properties.py
Labels: documentation

#63 feat(docs): Try to trigger build again
  honeybee_schema/energy/simulation.py
Labels: documentation

#66 feat(constructionset): Refactor ConstructionSet schema
  honeybee_schema/energy/constructionset.py
Labels: enhancement

#67 fix(load): Fix bug in the documentation of un-abridged loads
  honeybee_schema/_openapi.py
  honeybee_schema/energy/load.py
  samples/construction_set/constructionset_abridged_complete.json
  samples/construction_set/constructionset_abridged_partial_exterior.json
  samples/construction_set/constructionset_complete.json
  samples/construction_set/constructionset_partial_exterior.json
  samples/model/model_complete_multi_zone_office.json
  samples/model/model_complete_office_floor.json
  samples/model/model_complete_patient_room.json
  samples/model/model_complete_single_zone_office.json
  samples/model/model_complete_user_data.json
  samples/model/model_energy_detailed_loads.json
  samples/model/model_energy_fixed_interval.json
  samples/model/model_energy_no_program.json
  samples/model/model_energy_properties_office.json
  samples/model/model_energy_shoe_box.json
  samples/program_type/program_type_abridged_kitchen.json
  samples/program_type/program_type_abridged_office.json
  samples/program_type/program_type_abridged_patient_room.json
  samples/program_type/program_type_abridged_plenum.json
  samples/program_type/program_type_office.json
  samples/program_type/program_type_plenum.json
  samples/schedule/schedule_fixedinterval_random_annual.json
  scripts/sample_construction_set.py
  scripts/sample_program_type.py
  tests/test_constructionset.py
  tests/test_program_type.py
Labels: bug, documentation, enhancement

#68 fix(load): Get rid of extra heirarchy in non-abridged loads
  .travis.yml
  honeybee_schema/energy/construction.py
  honeybee_schema/energy/load.py
Labels: bug

#69 fix(ci): Use Python 3.7 for docs generation
  .travis.yml
Labels: bug

#70 docs(readme): Increment to Python 3.7
  README.md
Labels: documentation

#74 fix(model): ModelEnergyProperties.constructions are now optional
  honeybee_schema/energy/properties.py
Labels: bug

#75 fix(constructionset): Differentiate sub-set class names from radiance
  honeybee_schema/energy/constructionset.py
  honeybee_schema/energy/hvac.py
  honeybee_schema/energy/load.py
  samples/construction_set/constructionset_abridged_complete.json
  samples/construction_set/constructionset_abridged_partial_exterior.json
  samples/construction_set/constructionset_complete.json
  samples/construction_set/constructionset_partial_exterior.json
  samples/model/model_complete_multi_zone_office.json
  samples/model/model_complete_office_floor.json
  samples/model/model_complete_patient_room.json
  samples/model/model_complete_single_zone_office.json
  samples/model/model_complete_user_data.json
  samples/model/model_energy_detailed_loads.json
  samples/model/model_energy_fixed_interval.json
  samples/model/model_energy_no_program.json
  samples/model/model_energy_properties_office.json
  samples/model/model_energy_shoe_box.json
  tests/test_constructionset.py
Labels: bug

#65 feat(radiance): Adding initial radiance schema materials.
  honeybee_schema/energy/construction.py
  honeybee_schema/radiance/__init__.py
  honeybee_schema/radiance/material.py
Labels: enhancement

#79 fix(samples): Update modifier samples to use null "modifier" properties
  samples/construction_set/constructionset_complete.json
  samples/construction_set/constructionset_partial_exterior.json
  samples/modifier/modifier_bsdf_klemsfull.json
  samples/modifier/modifier_glass_air_boundary.json
  samples/modifier/modifier_glass_generic_exterior_window.json
  samples/modifier/modifier_glow_white.json
  samples/modifier/modifier_light_green_spotlight.json
  samples/modifier/modifier_plastic_black.json
  samples/modifier/modifier_plastic_generic_ceiling.json
  samples/modifier/modifier_plastic_generic_wall.json
  samples/modifier/modifier_trans_tree_foliage.json
  samples/modifier_set/modifierset_abridged_complete.json
  samples/modifier_set/modifierset_abridged_partial_exterior.json
  samples/modifier_set/modifierset_complete.json
  samples/modifier_set/modifierset_partial_exterior.json
  samples/schedule/schedule_fixedinterval_random_annual.json
Labels: bug, documentation

#87 fix(openapi): add format for array items
  honeybee_schema/_openapi.py
Labels: bug

#100 docs(samples): Add a sample with more than 4 vertices for sub-faces
  samples/model/model_5vertex_sub_faces.json
  scripts/sample_model.py
  tests/test_model.py
Labels: documentation

#105 docs(samples): Add samples and tests for BSDF and Mirror Materials
  samples/modifier/modifier_bsdf_klemsfull.json
  samples/modifier/modifier_mirror_invisible.json
  samples/modifier/modifier_mirror_typical.json
  scripts/sample_modifier.py
  tests/test_modifier.py
Labels: documentation

#109 docs(samples): Add samples for dynamic radiance geometry
  samples/model/model_radiance_dynamic_states.json
  samples/state/aperture_state_abridged_bsdf.json
  samples/state/aperture_state_abridged_electrochromic.json
  samples/state/aperture_state_abridged_shades.json
  samples/state/shade_state_abridged_snow.json
  samples/state/shade_state_abridged_tree_foliage.json
  scripts/sample_model.py
  scripts/sample_state.py
Labels: documentation
