Repository ladybug-tools/honeybee-schema, pull requests merged in 2020-11, with the labels that each got.

#208 fix(release asset): make the names consistent
  .releaserc.json
  .travis.yml
Labels: enhancement

#211 fix(openapi): Put back the default key for model version
  docs.py
  honeybee_schema/model.py
  samples/model/model_energy_afn.hbjson
  samples/model/model_energy_allair_hvac.hbjson
  samples/model/model_energy_doas_hvac.hbjson
  samples/model/model_energy_window_ac.hbjson
  samples/model/model_energy_window_ventilation.hbjson
  samples/model/model_radiance_grid_views.hbjson
Labels: bug

#212 fix(travis): Fix the deploy stage
  .travis.yml
Labels: bug

#213 docs(readme): Update readme
  README.md
  dev-requirements.txt
Labels: dependencies, documentation

#214 style(requirements): Ensure dependencies are listed only once
  requirements.txt
Labels: dependencies
