Repository ladybug-tools/honeybee-schema, pull requests merged in 2020-07, with the labels that each got.

#163 ci(docs): use versioned docs generated by semantic-release
  .travis.yml
Labels: documentation

#165 feat(ventcool): Add objects for simple window-based ventilative cooling
  honeybee_schema/energy/properties.py
  honeybee_schema/energy/ventcool.py
  samples/model/model_energy_window_ventilation.json
  samples/ventcool/ventilation_control_detailed.json
  samples/ventcool/ventilation_control_simple.json
  samples/ventcool/ventilation_opening_default.json
  scripts/sample_hvac.py
  scripts/sample_model.py
  scripts/sample_ventcool.py
  tests/test_model.py
  tests/test_ventcool.py
Labels: new development

#175 ci(docs): Include schema version in Model.version default
  docs.py
Labels: bug

#177 fix(wea): Update Wea schema to include datetimes
  honeybee_schema/radiance/wea.py
Labels: enhancement
