Repository ladybug-tools/honeybee-schema, pull requests merged in 2020-05, with the labels that each got.

#120 fix(solar): Change default solar distribution to FullExteriorWithReflect
  honeybee_schema/energy/simulation.py
  samples/model/model_5vertex_sub_faces_interior.json
  samples/simulation_parameter/simulation_par_detailed.json
  samples/simulation_parameter/simulation_par_simple.json
  scripts/sample_model.py
Labels: enhancement

#122 fix(rad-modifier): set default modifier to Optional Void
  honeybee_schema/radiance/modifier.py
Labels: enhancement

#124 docs(samples): Update Sample with dynamic radiance objects
  samples/model/model_radiance_dynamic_states.json
  samples/state/aperture_state_abridged_shades.json
  samples/state/shade_state_abridged_tree_foliage.json
  scripts/sample_model.py
  scripts/sample_state.py
Labels: documentation

#126 fix(model): Remove north from Model properties
  honeybee_schema/energy/properties.py
  honeybee_schema/energy/simulation.py
  honeybee_schema/model.py
  samples/construction_set/constructionset_complete.json
  samples/construction_set/constructionset_partial_exterior.json
  samples/model/model_5vertex_sub_faces.json
  samples/model/model_5vertex_sub_faces_interior.json
  samples/model/model_complete_multi_zone_office.json
  samples/model/model_complete_multiroom_radiance.json
  samples/model/model_complete_office_floor.json
  samples/model/model_complete_patient_room.json
  samples/model/model_complete_single_zone_office.json
  samples/model/model_complete_user_data.json
  samples/model/model_energy_detailed_loads.json
  samples/model/model_energy_fixed_interval.json
  samples/model/model_energy_no_program.json
  samples/model/model_energy_properties_office.json
  samples/model/model_energy_shoe_box.json
  samples/model/model_radiance_dynamic_states.json
  samples/modifier_set/modifierset_abridged_complete.json
  samples/modifier_set/modifierset_abridged_partial_exterior.json
  samples/modifier_set/modifierset_complete.json
  samples/modifier_set/modifierset_partial_exterior.json
  samples/schedule/schedule_fixedinterval_random_annual.json
  samples/simulation_parameter/simulation_par_detailed.json
  samples/simulation_parameter/simulation_par_simple.json
  scripts/sample_model.py
Labels: enhancement

#133 feat(radiance): Add schemas for SensorGrid and View
  honeybee_schema/radiance/asset.py
  honeybee_schema/radiance/modifier.py
  honeybee_schema/radiance/modifierset.py
  honeybee_schema/radiance/state.py
  samples/modifier/modifier_metal.json
  samples/radiance_asset/sensor_grid_detailed.json
  samples/radiance_asset/sensor_grid_simple.json
  samples/radiance_asset/view_parallel.json
  samples/radiance_asset/view_perspective.json
  scripts/sample_modifier.py
  scripts/sample_radiance_asset.py
  tests/test_modifier.py
  tests/test_radiance_asset.py
Labels: new development

#136 feat(light_path): Add light_path property for SensorGrid and View
  honeybee_schema/radiance/asset.py
Labels: enhancement

#141 fix(simulationparameter): Change default to include html
  honeybee_schema/energy/simulation.py
Labels: enhancement

#139 fix(openapi-spec): add duplicate enums
  honeybee_schema/_openapi.py
Labels: bug

#143 feat(lightsource): Add schemas for skies and light sources
  docs.py
  honeybee_schema/energy/designday.py
  honeybee_schema/radiance/lightsource.py
  honeybee_schema/radiance/wea.py
  samples/light_source/sky_certian_irradiance.json
  samples/light_source/sky_cie.json
  samples/light_source/sky_climate_based.json
  samples/light_source/sky_matrix.json
  samples/light_source/sun_matrix.json
  scripts/sample_light_source.py
  scripts/wea/denver.wea
  tests/test_light_source.py
Labels: new development

#145 feat(room): Add story property to Room
  honeybee_schema/model.py
Labels: enhancement

#147 feat(energy): Upgrade ShadowClaculation schema to use OpenStudio 3.0
  honeybee_schema/energy/simulation.py
  samples/simulation_parameter/simulation_par_detailed.json
  samples/simulation_parameter/simulation_par_simple.json
  scripts/sample_simulation.py
Labels: dependencies, enhancement

#148 fix(typos): Fix a few typos and update style to flake8
  honeybee_schema/_base.py
  honeybee_schema/boundarycondition.py
  honeybee_schema/energy/_base.py
  honeybee_schema/energy/construction.py
  honeybee_schema/energy/constructionset.py
  honeybee_schema/energy/designday.py
  honeybee_schema/energy/hvac.py
  honeybee_schema/energy/load.py
  honeybee_schema/energy/material.py
  honeybee_schema/energy/programtype.py
  honeybee_schema/energy/properties.py
  honeybee_schema/energy/schedule.py
  honeybee_schema/energy/simulation.py
  honeybee_schema/geometry.py
  honeybee_schema/model.py
  honeybee_schema/radiance/_base.py
  honeybee_schema/radiance/asset.py
  honeybee_schema/radiance/lightsource.py
  honeybee_schema/radiance/modifier.py
  honeybee_schema/radiance/modifierset.py
  honeybee_schema/radiance/properties.py
  honeybee_schema/radiance/state.py
  honeybee_schema/radiance/wea.py
Labels: bug, documentation

#149 fix(tolerance): Do not make bypassing checks the default
  honeybee_schema/model.py
Labels: enhancement

#150 fix(construction): Shade materials are not useable in WindowConstruction
  honeybee_schema/energy/construction.py
Labels: bug
